### ISSUE TITLE
Final primitives in wrappedconfig don't seem to read from files

### ISSUE THREAD

**Issue by sisby-folk** [QuiltMC/quilt-config#9]
In the docs for [WrappedConfig](https://github.com/QuiltMC/quilt-config/blob/638df034d90d9429b47d2b675f12b1ca0b027d19/src/main/java/org/quiltmc/config/api/Config.java#L150), there's a recommendation to use `boolean`, and an assertion that all fields must be `final`
![image](https://user-images.githubusercontent.com/55819817/235873965-e5162abd-9485-49ad-8e10-6b6c91d42236.png)

The latter is definitely right - there's a startup crash if you don't, but the former seemingly prevents values other than the default from ever loading in.

To reproduce:
 - Create a `public final boolean` config field with default true.
 - Set it to false in the config file.
 - Watch as it returns true in the code.

Using `Boolean` doesn't seem to have this problem. Not really sure _how_, but it's our workaround for now.
This is all 1.19.2, so I'm unsure if anything's moved around.

**Comment by TheGlitch76** [comment]
This is a fundamental problem with wrapped configs. The new `ReflectiveConfig` system will replace `WrappedConfig` starting in Loader `0.20` (hopefully!), and won't have this issue.

**Comment by sisby-folk** [comment]
can the docs be updated to reflect this?

**Comment by TheGlitch76** [comment]
None of this is released yet

**Comment by sisby-folk** [comment]
I meant changing `boolean` in the docs to reflect the fact that it can't be
used

**Comment by OroArmor** [comment]
Was this fixed with the new update?

**Comment by sisby-folk** [comment]
Uh, how do you even do primitives in ReflectiveConfig? I don't think i'm getting it.

when field is `final boolean` in reflective in 1.1.0 beta 3:
`Class 'java.lang.Boolean' of field 'preventAdvancementBroadcasts' of config class 'folk.sisby.crunchy_crunchy_advancements.CrunchyConfig'is not a valid config value: it must be a TrackedValue or implement org.quiltmc.loader.api.Config.Section`

**Comment by AlexIIL** [comment]
I think every field in a `ReflectiveConfig` must be a `TrackedValue`, and not a primitive - you can create them with `ReflectiveConfig.value()`

**Comment by sisby-folk** [comment]
Ah so you can just call `value(false)` seeing as you're in a ReflectiveConfig. 

To answer the question - no, this does not solve the problem. `TrackedValue<Boolean>` (for reflective) and `Boolean` are both not the same as `boolean`, so the docs still need to be updated to use the object types in both cases

**Comment by ix0rai** [comment]
all javadocs have been corrected as far as I can tell, this can be closed

**Comment by sisby-folk** [comment]
? 
![image](https://github.com/QuiltMC/quilt-config/assets/55819817/adde4584-c594-4882-bd03-2da8bbb1fe4b)
